# general settings
name: rsfnet_saliency_ppr10k_c
model_type: RRSFNetModel
num_gpu: 1  # set num_gpu: 0 for cpu mode
manual_seed: 0

# dataset and data loader settings
datasets:
  train:
    name: PPR10K
    type: RSFNetDataset
    dataroot_gt: datasets/PPR10K/train_val_images_tif_360p/target_c
    dataroot_lq: datasets/PPR10K/train_val_images_tif_360p/source
    dataroot_mask: datasets/PPR10K/masks_360p
    meta_info_file: datasets/PPR10K/train.txt
    filename_tmpl: '{}'
    filename_tmpl_mask: '{}'
    mask_num: 1
    io_backend:
      type: disk
      # (for lmdb)
      # type: lmdb

    gt_size: 256
    scale: 1
    use_hflip: true
    use_rot: false
    mean: 0.5
    std: 0.5

    # data loader
    use_shuffle: true
    num_worker_per_gpu: 6
    batch_size_per_gpu: 16
    dataset_enlarge_ratio: 1
    prefetch_mode: ~

  val:
    name: PPR10K
    type: RSFNetDataset
    dataroot_gt: datasets/PPR10K/train_val_images_tif_360p/target_c
    dataroot_lq: datasets/PPR10K/train_val_images_tif_360p/source
    dataroot_mask: datasets/PPR10K/masks_360p
    meta_info_file: datasets/PPR10K/test.txt
    filename_tmpl: '{}'
    filename_tmpl_mask: '{}'
    mask_num: 1
    io_backend:
      type: disk

    scale: 1
    mean: 0.5
    std: 0.5

# network structures
network_g:
  type: RSFNet
  pretrained: 'torchvision://resnet18'
  init_weight: false
  max_down_size: 32
  complementary_mask: true
  cache: false
  backbone:
    type: 'ResNet'
    depth: 18
    num_stages: 4
    out_indices: [0, 1, 2, 3] # C2, C3, C4, C5
    frozen_stages: -1
    style: pytorch
  neck:
    type: 'FPN'
    in_channels: [64, 128, 256, 512]
    out_channels: 64
    start_level: 0
    num_outs: 4
  head:
    type: SegRecolorHead
    num_segs: 1
    param_channels: 2
    in_channels: 256
    stacked_convs: 4
    param_nums: 11
    seg_feat_channels: 256
    with_deform: false
  graph:
    type: Renderer_N10

# path
path:
 #pretrain_network_g: experiments/xxx.pth
  strict_load_g: false
  #resume_state: experiments/xxx.state

# training settings
train:
#  ema_decay: 0.999
  optim_g:
    type: Adam
    lr: !!float 2e-4
    weight_decay: 0
    betas: [0.9, 0.99]

  scheduler:
    type: CosineAnnealingRestartLR
    periods: [250000, 250000, 250000, 250000, 250000, 250000, 250000, 250000]
    restart_weights: [1, 1, 1, 1, 1, 1, 1, 1]
    eta_min: !!float 1e-7

  total_iter: 2000000
  warmup_iter: -1  # no warm up

  # losses
  pixel_opt:
    type: L1Loss
    loss_weight: 1.0
    reduction: mean
  mask_opt:
    type: DiceLoss
    loss_weight: 1.0

# validation settings
val:
  val_freq: !!float 5e3
  save_img: false
  pbar: true

  metrics:
    psnr: # metric name, can be arbitrary
      type: calculate_psnr
      crop_border: 2
      test_y_channel: false
    ssim:
      type: calculate_ssim
      crop_border: 2
      test_y_channel: false

# logging settings
logger:
  print_freq: 100
  save_checkpoint_freq: !!float 5e3
  use_tb_logger: true
  wandb:
    project: ~
    resume_id: ~

# visdom settings
#visuals:
#  show_freq: 50
#  display_port: 8115
#  display_server: http://localhost
#  path: experiments/rsfnet_saliency_ppr10k_c/visuals

# dist training settings
dist_params:
  backend: nccl
  port: 29500
